### PR TITLE
Support for binary messages (websocket opcode 2)

### PR DESCRIPTION
**Pull request by motla**
Hi! First, thanks a lot for your work on this plugin. It has been very helpful for my project.
I just implemented and tested the support for websocket binary messages (Android and iOS).
Feel free to merge it to your tree and update plugin version.
Have a great day!

### CODE REVIEW

**Comment by becvert** [comment]
Hello @motla 
I'm not using this plugin in my current projects so I won't test your changes,
but it looks rather good to me.
Can you update the files Changelog.md, package.json and plugin.xml accordingly with a new version number 1.6.0.
Then I'll merge.
Thank you

**Comment by motla** [comment]
There you go. Thank you

**Comment by motla** [comment]
Sorry I'm quite new to Github, I clicked "close the PR" but are you still able to merge it?

**Comment by becvert** [comment]
Nope. I can't merge now. You'll have to recreate your repo.
Great job otherwise. Thank you.

**Pull request closed without merging**
